[basic]
description = ""
published = ""
remediation = "请参考官方安全公告，及时安装安全更新或升级到最新版本。"
score = 5
severity = "MEDIUM"
sources = ["avd"]
title = "** REJECT **"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-1999-1594"]
ave_id = "AVE-1999-0006"

[meta]
collected_at = "2026-07-11T21:44:18.529896054+00:00"
status = "completed"

[references]
urls = []
