[basic]
description = ""
published = ""
remediation = "请参考官方安全公告，及时安装安全更新或升级到最新版本。"
score = 5
severity = "MEDIUM"
sources = ["avd"]
title = "** REJECT **"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-1999-1596"]
ave_id = "AVE-1999-0005"

[meta]
collected_at = "2026-07-11T22:02:05.950292239+00:00"
status = "completed"

[references]
urls = []
