[basic]
description = ""
published = ""
remediation = "请参考官方安全公告，及时安装安全更新或升级到最新版本。"
score = 5
severity = "MEDIUM"
sources = ["cve"]
title = "CVE-1999-0001"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-1999-0001"]
ave_id = "AVE-1999-0013"

[meta]
collected_at = "2026-07-11T21:37:29.062594433+00:00"
status = "completed"

[references]
urls = []
