[basic]
description = "CVE-1999-1593: 目前没有详细的漏洞描述。请参考相关安全公告获取更多信息。"
published = "unknown"
remediation = "请参考官方安全公告，及时安装安全更新或升级到最新版本。"
score = 5.0
severity = "MEDIUM"
sources = ["avd"]
title = "CVE-1999-1593 漏洞详情"
updated = "unknown"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-1999-1593"]
ave_id = "AVE-1999-0004"

[meta]
collected_at = "2026-07-11T20:57:55.350272642+00:00"
status = "completed"

[references]
urls = []
