[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["exploitdb"]
title = "CVE-1999-0009 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-1999-0009"]
ave_id = "AVE-1999-0207"
cve_id = "CVE-1999-0009"

[meta]
collected_at = "2026-07-10T21:07:55.836803535+00:00"
status = "completed"

[references]
urls = []
