[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["redhat"]
title = "CVE-1999-0210 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-1999-0210"]
ave_id = "AVE-1999-0007"
cve_id = "CVE-1999-0210"

[meta]
collected_at = "2026-07-11T16:25:56.925050267+00:00"
status = "completed"

[references]
urls = []
