[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["tenable"]
title = "CVE-1999-1109 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-1999-1109"]
ave_id = "AVE-1999-0205"
cve_id = "CVE-1999-1109"

[meta]
collected_at = "2026-07-10T20:59:50.664731920+00:00"
status = "completed"

[references]
urls = []
