[basic]
description = 'NetBSD 1.3.3 操作系统中，mount 命令在某些情况下未能正确遵循文件系统的 "noexec" 标志设置，允许本地用户在被标记为不可执行（noexec）的文件系统中执行程序。这一漏洞破坏了系统的安全策略，攻击者可能利用此特性绕过 noexec 限制执行恶意代码，从而获取敏感信息或进一步实施攻击。'
published = "1999-03-17"
remediation = "升级 NetBSD 系统至 1.4 或更高版本，或安装厂商发布的安全补丁以修复 mount 命令处理 noexec 标志的问题。"
score = 4.6
severity = "MEDIUM"
sources = [
    "NVD",
    "CVE",
]
title = "NetBSD 1.3.3 mount 未正确遵循 noexec 标志导致本地权限提升漏洞"
updated = "2026-06-16"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-1999-0422"]
ave_id = "AVE-1999-0301"

[meta]
collected_at = "2026-07-11T23:25:30.178642838+00:00"
status = "completed"

[references]
urls = [
    "https://nvd.nist.gov/vuln/detail/CVE-1999-0422",
    "https://exchange.xforce.ibmcloud.com/vulnerabilities/CVE-1999-0422",
]
