[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["redhat"]
title = "CVE-1999-0077 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-1999-0077"]
ave_id = "AVE-1999-0003"
cve_id = "CVE-1999-0077"

[meta]
collected_at = "2026-07-11T04:25:36.550107827+00:00"
status = "completed"

[references]
urls = []
