[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["tenable"]
title = "CVE-1999-0096 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-1999-0096"]
ave_id = "AVE-1999-0002"

[meta]
collected_at = "2026-07-11T19:31:36.298212423+00:00"
status = "completed"

[references]
urls = []
