[basic]
description = "ptylogin 是 Unix 系统中由 Marc Schaefer 开发的登录程序，存在安全漏洞。攻击者可通过锁定调制解调器、利用调制解调器拨号或获取密码等方式，发动拒绝服务攻击或获取未授权访问，影响系统可用性及机密性。"
published = "2001-03-12"
remediation = "升级 ptylogin 至已修复版本，限制非授权用户访问该程序，并配置调制解调器权限防止被滥用。"
score = 7.5
severity = "HIGH"
sources = [
    "cve",
    "nvd",
]
title = "Marc Schaefer ptylogin 拒绝服务及未授权访问漏洞"
updated = "2026-06-16"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-1999-0359"]
ave_id = "AVE-1999-0077"
cve_id = "CVE-1999-0359"

[meta]
collected_at = "2026-07-10T12:52:04Z"
status = "completed"

[references]
urls = ["https://exchange.xforce.ibmcloud.com/vulnerabilities/CVE-1999-0359"]
