[basic]
description = "华盛顿大学实现的 IMAP 和 POP 邮件服务器软件存在缓冲区溢出漏洞。远程攻击者无需认证即可利用 IMAP 登录过程中的缓冲区溢出，向 /etc/passwd 文件添加特权账户，从而完全控制受影响系统。该漏洞影响所有运行 UW IMAP 及 POP 服务的 Linux 系统。"
published = "1997-04-07"
remediation = "升级华盛顿大学 IMAP 服务器至最新版，或禁用 IMAP/POP 服务并使用更安全的替代方案如 Dovecot。若无法升级，限制 143 端口访问并配置防火墙。"
score = 10.0
severity = "CRITICAL"
sources = [
    "nvd",
    "exploitdb",
]
title = "华盛顿大学 IMAP 与 POP 服务器缓冲区溢出漏洞"
updated = "2026-06-16"

[exploit]
exp_urls = []
poc_urls = ["https://www.exploit-db.com/exploits/340"]

[id]
aliases = ["CVE-1999-0042"]
ave_id = "AVE-1999-0202"

[meta]
collected_at = "2026-07-11T23:18:07.300374105+00:00"
status = "completed"

[references]
urls = ["https://exchange.xforce.ibmcloud.com/vulnerabilities/CVE-1999-0042"]
