[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["redhat"]
title = "CVE-1999-0018 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-1999-0018"]
ave_id = "AVE-1999-0005"

[meta]
collected_at = "2026-07-11T19:12:48.986688944+00:00"
status = "completed"

[references]
urls = []
