
[id]
  ave_id = "AVE-2015-0011"
  cve_id = "CVE-2015-10116"
  aliases = ["CVE-2015-10116"]

[basic]
  title = "WordPress plugin favicon-by-realfavicongenerator 跨站请求伪造漏洞(CVE-2015-10116)"
  description = ""
  severity = "MEDIUM"
  score = 5.4
  sources = ["avd"]
  published = "2023-06-06"
  updated = ""
  remediation = "Refer to vendor advisory and upgrade to fixed version."

[score]
  cvss_v2 = 5.0
  cvss_v2_vector = "AV:N/AC:L/Au:N/C:N/I:P/A:N"
  cvss_v3 = 5.4
  cvss_v3_vector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N"
  cvss_v4 = 5.1
  cvss_v4_vector = "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:L/VI:L/VA:N/SC:N/SI:N/SA:N"

[exploit]
poc_urls = []
exp_urls = []

[references]
urls = []

[meta]
status = "completed"
collected_at = "2026-07-10T06:24:59.203564733+00:00"
