
[id]
  ave_id = "AVE-2015-0017"
  cve_id = "CVE-2015-10122"
  aliases = ["CVE-2015-10122"]

[basic]
  title = "WordPress Plugin wp-donate SQL注入漏洞(CVE-2015-10122)"
  description = ""
  severity = "HIGH"
  score = 8.6
  sources = ["avd"]
  published = "2023-07-18"
  updated = ""
  remediation = "Refer to vendor advisory and upgrade to fixed version."

[score]
  cvss_v2 = 7.5
  cvss_v2_vector = "AV:N/AC:L/Au:N/C:P/I:P/A:P"
  cvss_v3 = 8.6
  cvss_v3_vector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:L"
  cvss_v4 = 8.7
  cvss_v4_vector = "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:L/VA:L/SC:N/SI:N/SA:N"

[exploit]
poc_urls = []
exp_urls = []

[references]
urls = []

[meta]
status = "completed"
collected_at = "2026-07-10T06:54:20.153002886+00:00"
