[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["kev"]
title = "CVE-2009-0238 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2009-0238"]
ave_id = "AVE-2009-0001"
cve_id = "CVE-2009-0238"

[meta]
collected_at = "2026-07-11T00:06:29.387287405+00:00"
status = "completed"

[references]
urls = []
