
[id]
  ave_id = "AVE-2016-0004"
  cve_id = "CVE-2016-15035"
  aliases = ["CVE-2016-15035"]

[basic]
  title = "RE-Chat 跨站脚本漏洞(CVE-2016-15035)"
  description = ""
  severity = "MEDIUM"
  score = 6.1
  sources = ["avd"]
  published = "2023-08-28"
  updated = ""
  remediation = "Refer to vendor advisory and upgrade to fixed version."

[score]
  cvss_v2 = 4.3
  cvss_v2_vector = "AV:N/AC:M/Au:N/C:N/I:P/A:N"
  cvss_v3 = 6.1
  cvss_v3_vector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N"
  cvss_v4 = 5.1
  cvss_v4_vector = "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:L/VI:L/VA:N/SC:N/SI:N/SA:N"

[exploit]
poc_urls = []
exp_urls = []

[references]
urls = []

[meta]
status = "completed"
collected_at = "2026-07-10T07:44:54.456789008+00:00"
