[basic]
description = "Vulnerability identified as CVE-2016-15032. Please refer to vendor advisory for details."
published = "2023-06-02"
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 6.1
severity = "MEDIUM"
sources = ["avd"]
title = "mback2k mh_httpbl 跨站脚本漏洞(CVE-2016-15032)"
updated = "2026-07-10"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2016-15032"]
ave_id = "AVE-2016-0001"
cve_id = "CVE-2016-15032"

[meta]
collected_at = "2026-07-10T06:54:25.404906187+00:00"
status = "completed"

[references]
urls = []

[score]
cvss_v2 = 4.3
cvss_v2_vector = "AV:N/AC:M/Au:N/C:N/I:P/A:N"
cvss_v3 = 6.1
cvss_v3_vector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N"
cvss_v4 = 5.1
cvss_v4_vector = "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:L/VI:L/VA:N/SC:N/SI:N/SA:N"
