[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["msrc"]
title = "CVE-2016-9535 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2016-9535"]
ave_id = "AVE-2016-0006"
cve_id = "CVE-2016-9535"

[meta]
collected_at = "2026-07-10T21:08:05.564303179+00:00"
status = "completed"

[references]
urls = []
