[id]
ave_id = "AVE-2016-0002"
cve_id = "CVE-2016-15033"
aliases = ["CVE-2016-15033"]

[basic]
title = "WordPress Plugin Delete All Comments 代码问题漏洞(CVE-2016-15033)"
description = ""
severity = "UNKNOWN"
score = 0.0
sources = ["avd"]
published = "2023-06-07"
updated = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."

[references]
urls = []

[exploit]
poc_urls = []
exp_urls = []

[meta]
status = "completed"
collected_at = "2026-07-10T06:54:25.482102071+00:00"
