[basic]
description = "Vulnerability identified as NUCLEI-HTTP-CNVD-2019-CNVD-2019-19299-YAML. Please refer to vendor advisory for details."
published = "2026-07-10"
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 5.0
severity = "MEDIUM"
sources = ["nuclei"]
title = "NUCLEI-HTTP-CNVD-2019-CNVD-2019-19299-YAML"
updated = "2026-07-10"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["NUCLEI-HTTP-CNVD-2019-CNVD-2019-19299-YAML"]
ave_id = "AVE-2026-0032"
cve_id = "NUCLEI-HTTP-CNVD-2019-CNVD-2019-19299-YAML"

[meta]
collected_at = "2026-07-10T18:35:11.950580355+00:00"
status = "completed"

[references]
urls = []
