[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["ghsa"]
title = "CVE-2026-48596"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = [
    "CVE-2026-48596",
    "GHSA-q7jx-v53g-848w",
]
ave_id = "AVE-2026-0076"
cve_id = "CVE-2026-48596"

[meta]
collected_at = "2026-07-10T20:58:40.311354414+00:00"
status = "completed"

[references]
urls = []
