[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["ghsa"]
title = "CVE-2026-48597"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = [
    "CVE-2026-48597",
    "GHSA-h74c-q9j7-mpcm",
]
ave_id = "AVE-2026-0077"
cve_id = "CVE-2026-48597"

[meta]
collected_at = "2026-07-10T21:07:10.700496392+00:00"
status = "completed"

[references]
urls = []
