[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["ghsa"]
title = "CVE-2026-48987"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = [
    "CVE-2026-48987",
    "GHSA-c2f9-4mc8-j656",
]
ave_id = "AVE-2026-0048"
cve_id = "CVE-2026-48987"

[meta]
collected_at = "2026-07-10T22:17:52.308526502+00:00"
status = "completed"

[references]
urls = []
