[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["github"]
title = "CVE-2026-0047"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2026-0047"]
ave_id = "AVE-2026-0073"
cve_id = "CVE-2026-0047"

[meta]
collected_at = "2026-07-10T21:03:22.269550161+00:00"
status = "completed"

[references]
urls = []
