[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["nuclei"]
title = "NUCLEI-HTTP-CNVD-2017-CNVD-2017-03561-YAML 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["NUCLEI-HTTP-CNVD-2017-CNVD-2017-03561-YAML"]
ave_id = "AVE-2026-0004"

[meta]
collected_at = "2026-07-11T20:52:31.960706275+00:00"
status = "completed"

[references]
urls = []
