[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["ghsa"]
title = "CVE-2026-49476"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = [
    "CVE-2026-49476",
    "GHSA-2wc2-fm75-p42x",
]
ave_id = "AVE-2026-0054"
cve_id = "CVE-2026-49476"

[meta]
collected_at = "2026-07-11T00:15:31.567719138+00:00"
status = "completed"

[references]
urls = []
