[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["nuclei"]
title = "NUCLEI-FILE-MALWARE-UNIVERSAL-1337-MALWARE-YAML 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["NUCLEI-FILE-MALWARE-UNIVERSAL-1337-MALWARE-YAML"]
ave_id = "AVE-2026-0001"
cve_id = "NUCLEI-FILE-MALWARE-UNIVERSAL-1337-MALWARE-YAML"

[meta]
collected_at = "2026-07-11T04:07:04.302587406+00:00"
status = "completed"

[references]
urls = []
