[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["nuclei"]
title = "NUCLEI-HTTP-CNVD-2019-CNVD-2019-01348-YAML 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["NUCLEI-HTTP-CNVD-2019-CNVD-2019-01348-YAML"]
ave_id = "AVE-2026-0006"
cve_id = "NUCLEI-HTTP-CNVD-2019-CNVD-2019-01348-YAML"

[meta]
collected_at = "2026-07-11T05:06:25.249313450+00:00"
status = "completed"

[references]
urls = []
