[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["ghsa"]
title = "CVE-2026-48595"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = [
    "CVE-2026-48595",
    "GHSA-9m9w-gxf7-rh8m",
]
ave_id = "AVE-2026-0041"
cve_id = "CVE-2026-48595"

[meta]
collected_at = "2026-07-10T20:55:31.340734009+00:00"
status = "completed"

[references]
urls = []
