[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["nuclei"]
title = "NUCLEI-HTTP-CNVD-2017-CNVD-2017-06001-YAML 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["NUCLEI-HTTP-CNVD-2017-CNVD-2017-06001-YAML"]
ave_id = "AVE-2026-0027"
cve_id = "NUCLEI-HTTP-CNVD-2017-CNVD-2017-06001-YAML"

[meta]
collected_at = "2026-07-10T20:59:23.035586095+00:00"
status = "completed"

[references]
urls = []
