[id]
ave_id = "AVE-2002-0002"
cve_id = "CVE-2002-0906"
aliases = ["CVE-2002-0906"]

[basic]
title = "CVE-2002-0906"
description = ""
severity = "UNKNOWN"
score = 0.0
sources = ["tenable"]
published = ""
updated = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."

[references]
urls = []

[exploit]
poc_urls = []
exp_urls = []

[meta]
status = "completed"
collected_at = "2026-07-10T10:50:53.827974884+00:00"
