[id]
ave_id = "AVE-2025-0004"
cve_id = "CVE-2025-46571"
aliases = [
    "CVE-2025-46571",
    "GHSA-8gh5-qqh8-hq3x",
]

[basic]
title = "CVE-2025-46571"
description = ""
severity = "UNKNOWN"
score = 0.0
sources = ["ghsa"]
published = ""
updated = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."

[references]
urls = []

[exploit]
poc_urls = []
exp_urls = []

[meta]
status = "completed"
collected_at = "2026-07-10T09:10:49.230410530+00:00"
