[id]
ave_id = "AVE-2000-0004"
cve_id = "CVE-2000-1221"
aliases = ["CVE-2000-1221"]

[basic]
title = "CVE-2000-1221"
description = ""
severity = "UNKNOWN"
score = 0.0
sources = ["osv"]
published = ""
updated = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."

[references]
urls = []

[exploit]
poc_urls = []
exp_urls = []

[meta]
status = "completed"
collected_at = "2026-07-10T11:01:55.332346733+00:00"
