[id]
ave_id = "AVE-2025-0013"
cve_id = "CVE-2025-24071"
aliases = ["CVE-2025-24071"]

[basic]
title = "CVE-2025-24071"
description = ""
severity = "UNKNOWN"
score = 0.0
sources = ["github"]
published = ""
updated = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."

[references]
urls = []

[exploit]
poc_urls = []
exp_urls = []

[meta]
status = "completed"
collected_at = "2026-07-10T11:12:19.070764453+00:00"
