[id]
ave_id = "AVE-2015-0002"
cve_id = "CVE-2015-10107"
aliases = ["CVE-2015-10107"]

[basic]
title = "WordPress Plugin Simplr Registration Form Plus 跨站脚本漏洞(CVE-2015-10107)"
description = ""
severity = "UNKNOWN"
score = 0.0
sources = ["avd"]
published = "2023-05-31"
updated = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."

[references]
urls = []

[exploit]
poc_urls = []
exp_urls = []

[meta]
status = "completed"
collected_at = "2026-07-10T04:57:52.944215765+00:00"
