[id]
ave_id = "AVE-2018-0006"
cve_id = "CVE-2018-13372"
aliases = ["CVE-2018-13372"]

[basic]
title = "CVE-2018-13372"
description = ""
severity = "UNKNOWN"
score = 0.0
sources = ["avd"]
published = ""
updated = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."

[references]
urls = []

[exploit]
poc_urls = []
exp_urls = []

[meta]
status = "completed"
collected_at = "2026-07-10T10:50:50.978169818+00:00"
