[id]
ave_id = "AVE-2015-0014"
cve_id = "CVE-2015-10119"
aliases = ["CVE-2015-10119"]

[basic]
title = "WordPress plugin view-all-posts-pages 跨站脚本漏洞(CVE-2015-10119)"
description = ""
severity = "UNKNOWN"
score = 0.0
sources = ["avd"]
published = "2023-07-11"
updated = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."

[references]
urls = []

[exploit]
poc_urls = []
exp_urls = []

[meta]
status = "completed"
collected_at = "2026-07-10T06:25:01.410001812+00:00"
