[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["osv"]
title = "CVE-2002-1271 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2002-1271"]
ave_id = "AVE-2002-0008"
cve_id = "CVE-2002-1271"

[meta]
collected_at = "2026-07-11T17:11:41.957903271+00:00"
status = "completed"

[references]
urls = []
