[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["osv"]
title = "CVE-2002-1146 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2002-1146"]
ave_id = "AVE-2002-0041"
cve_id = "CVE-2002-1146"

[meta]
collected_at = "2026-07-10T21:15:12.271617361+00:00"
status = "completed"

[references]
urls = []
