[affected]
product = "Sendmail SMRSH"
vendor = "Sendmail"

[basic]
description = "Sendmail Consortium的受限Shell（SMRSH）存在于Sendmail 8.12.6、8.11.6-15及之后版本中。由于对特殊字符过滤不严，攻击者可以通过在'||'序列或'/'字符后插入额外命令来绕过smrsh的受限执行环境，导致权限绕过和任意命令执行，危害系统安全。"
published = "2002-10-11"
remediation = "升级Sendmail至最新版本或安装厂商发布的安全补丁。建议在smrsh配置中严格限制可执行命令列表，并对输入中的'||'和'/'等特殊字符进行过滤，避免绕过受限执行环境。"
score = 4.6
severity = "MEDIUM"
sources = [
    "osv",
    "nvd",
]
title = "Sendmail SMRSH 受限Shell命令执行漏洞"
updated = "2026-06-16"

[exploit]
exp_urls = []
nuclei_templates = []
poc_urls = []

[id]
aliases = ["CVE-2002-1165"]
ave_id = "AVE-2002-0046"
cve_id = "CVE-2002-1165"

[meta]
collected_at = "2026-07-11T00:00:33Z"
status = "completed"

[references]
urls = [
    "https://nvd.nist.gov/vuln/detail/CVE-2002-1165",
    "http://www.sendmail.org/smrsh.adv.txt",
    "http://www.securityfocus.com/bid/5845",
    "http://secunia.com/advisories/7826",
    "http://www.iss.net/security_center/static/10232.php",
    "http://www.redhat.com/support/errata/RHSA-2003-073.html",
    "http://www.mandriva.com/security/advisories?name=MDKSA-2002:083",
    "http://distro.conectiva.com.br/atualizacoes/?id=a&anuncio=000532",
    "http://marc.info/?l=bugtraq&m=103350914307274&w=2",
]
