[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["osv"]
title = "CVE-2002-1159 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2002-1159"]
ave_id = "AVE-2002-0045"
cve_id = "CVE-2002-1159"

[meta]
collected_at = "2026-07-10T23:18:28.800306497+00:00"
status = "completed"

[references]
urls = []
