[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["osv"]
title = "CVE-2002-1235 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2002-1235"]
ave_id = "AVE-2002-0007"
cve_id = "CVE-2002-1235"

[meta]
collected_at = "2026-07-11T17:10:54.962447553+00:00"
status = "completed"

[references]
urls = []
