[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["osv"]
title = "CVE-2002-1049 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2002-1049"]
ave_id = "AVE-2002-0037"
cve_id = "CVE-2002-1049"

[meta]
collected_at = "2026-07-10T20:56:52.767465374+00:00"
status = "completed"

[references]
urls = []
