[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["avd"]
title = "CVE-2018-25111 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2018-25111"]
ave_id = "AVE-2018-0040"
cve_id = "CVE-2018-25111"

[meta]
collected_at = "2026-07-11T00:10:15.324678431+00:00"
status = "completed"

[references]
urls = []
