[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["avd"]
title = "CVE-2018-25096 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2018-25096"]
ave_id = "AVE-2018-0026"
cve_id = "CVE-2018-25096"

[meta]
collected_at = "2026-07-10T21:02:37.555634970+00:00"
status = "completed"

[references]
urls = []
