[basic]
description = "Vulnerability identified as CVE-2018-25088. Please refer to vendor advisory for details."
published = "2026-07-10"
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 5.0
severity = "MEDIUM"
sources = ["avd"]
title = "CVE-2018-25088 vulnerability"
updated = "2026-07-10"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2018-25088"]
ave_id = "AVE-2018-0018"
cve_id = "CVE-2018-25088"

[meta]
collected_at = "2026-07-10T12:52:01.549899568+00:00"
status = "completed"

[references]
urls = []
