[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["avd"]
title = "CVE-2018-25106 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2018-25106"]
ave_id = "AVE-2018-0035"
cve_id = "CVE-2018-25106"

[meta]
collected_at = "2026-07-10T21:30:38.885149893+00:00"
status = "completed"

[references]
urls = []
