[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["avd"]
title = "CVE-2018-25094 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2018-25094"]
ave_id = "AVE-2018-0024"
cve_id = "CVE-2018-25094"

[meta]
collected_at = "2026-07-10T20:55:40.129269011+00:00"
status = "completed"

[references]
urls = []
