[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["msrc"]
title = "CVE-2006-10002 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2006-10002"]
ave_id = "AVE-2006-0001"

[meta]
collected_at = "2026-07-11T19:27:35.171692451+00:00"
status = "completed"

[references]
urls = []
