[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["tenable"]
title = "CVE-2007-4770 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2007-4770"]
ave_id = "AVE-2007-0009"
cve_id = "CVE-2007-4770"

[meta]
collected_at = "2026-07-11T00:08:49.200933098+00:00"
status = "completed"

[references]
urls = []
