[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["kev"]
title = "CVE-2007-5659 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2007-5659"]
ave_id = "AVE-2007-0003"
cve_id = "CVE-2007-5659"

[meta]
collected_at = "2026-07-11T17:13:56.732707510+00:00"
status = "completed"

[references]
urls = []
