[basic]
description = "Vulnerability identified as CVE-2025-38352. Please refer to vendor advisory for details."
published = "2026-07-10"
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 5.0
severity = "MEDIUM"
sources = ["github"]
title = "Vulnerability in CVE-2025-38352"
updated = "2026-07-10"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2025-38352"]
ave_id = "AVE-2025-0027"
cve_id = "CVE-2025-38352"

[meta]
collected_at = "2026-07-10T12:52:04.990621094+00:00"
status = "completed"

[references]
urls = []
