[basic]
description = """
Hitachi Virtual Storage Platform 是 Hitachi 公司的企业级存储阵列系统，其管理界面（维护工具）存在授权缺陷漏洞。攻击者可在未授权情况下通过维护工具执行敏感操作。
受影响版本中，维护工具对维护功能的访问控制验证不完整，低权限用户可通过构造特定请求绕过授权检查，获取未经授权的管理操作权限，可能导致数据泄露或配置篡改。
修复版本中通过升级微码（固件）到指定版本来解决该授权缺陷，官方建议受影响用户尽快执行永久修复措施，即更换为已修复的微码版本。
解决建议
将组件 Hitachi:Virtual Storage Platform E390/E590/E790/E990/E1090/E390H/E590H/E790H/E1090H 升级至 93-07-26-xx/00 及以上版本
将组件 Hitachi:Virtual Storage Platform 5100/5500/5100H/5500H/5200/5600/5200H/5600H 升级至 90-09-27-00/00 及以上版本
将组件 Hitachi:Virtual Storage Platform G130/G150/G350/G370/G700/G900/F350/F370/F700/F900 升级至 88-08-16-xx/00 及以上版本"""
published = "2026-06-29"
remediation = """
将组件 Hitachi:Virtual Storage Platform E390/E590/E790/E990/E1090/E390H/E590H/E790H/E1090H 升级至 93-07-26-xx/00 及以上版本
将组件 Hitachi:Virtual Storage Platform 5100/5500/5100H/5500H/5200/5600/5200H/5600H 升级至 90-09-27-00/00 及以上版本
将组件 Hitachi:Virtual Storage Platform G130/G150/G350/G370/G700/G900/F350/F370/F700/F900 升级至 88-08-16-xx/00 及以上版本"""
score = 8.1
severity = "HIGH"
sources = ["avd"]
title = "Hitachi Virtual Storage Platform 维护工具授权缺陷漏洞(CVE-2025-2902)"
updated = "2026-07-10"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2025-2902"]
ave_id = "AVE-2025-0002"
cve_id = "CVE-2025-2902"

[meta]
collected_at = "2026-07-10T02:54:42.772288331+00:00"
status = "completed"

[references]
urls = []

[score]
cvss_v2 = 7.5
cvss_v2_vector = "AV:N/AC:L/Au:N/C:P/I:P/A:P"
cvss_v3 = 8.1
cvss_v3_vector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N"
cvss_v4 = 8.6
cvss_v4_vector = "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:N/SC:N/SI:N/SA:N"
