[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["github"]
title = "CVE-2025-0282"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2025-0282"]
ave_id = "AVE-2025-0002"

[meta]
collected_at = "2026-07-11T19:46:03.792213442+00:00"
status = "completed"

[references]
urls = []
