[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["avd"]
title = "CVE-2000-1249 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2000-1249"]
ave_id = "AVE-2000-0002"
cve_id = "CVE-2000-1249"

[meta]
collected_at = "2026-07-11T17:14:44.522341271+00:00"
status = "completed"

[references]
urls = []
