[basic]
description = "screen and rxvt in Red Hat Linux 6.0 do not properly set the modes of tty devices, which allows local users to write to other ttys."
published = "1999-06-06"
remediation = "升级 Red Hat Linux 至修复版本。参考 Red Hat 安全公告 RHSA-1999:014-01。"
score = 5.0
severity = "MEDIUM"
sources = [
    "redhat",
    "nvd",
]
title = "screen 和 rxvt TTY 权限配置不当导致本地用户可写入其他 TTY"
updated = "2026-06-16"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2000-0364"]
ave_id = "AVE-2000-0022"
cve_id = "CVE-2000-0364"

[meta]
collected_at = "2026-07-10T10:18:58Z"
status = "completed"

[references]
urls = [
    "https://nvd.nist.gov/vuln/detail/CVE-2000-0364",
    "https://access.redhat.com/security/cve/CVE-2000-0364",
    "http://www.redhat.com/corp/support/errata/RHSA1999014_01.html",
    "http://www.securityfocus.com/bid/309",
    "http://marc.info/?l=bugtraq&m=92877527701347&w=2",
    "http://marc.info/?l=bugtraq&m=92886009012161&w=2",
]

[score]
cvss_v2 = 5.0
cvss_v2_vector = "AV:N/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3 = 5.0
cvss_v3_vector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:P"
cvss_v4 = 0.0
cvss_v4_vector = ""
