[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["hwpoc"]
title = "HWPOC-2023-000475df"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["HWPOC-2023-000475df"]
ave_id = "AVE-2023-0004"
cve_id = "HWPOC-2023-000475df"

[meta]
collected_at = "2026-07-11T05:06:00.653648652+00:00"
status = "completed"

[references]
urls = []
