[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["hwpoc"]
title = "CVE-2023-4966"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2023-4966"]
ave_id = "AVE-2023-0003"
cve_id = "CVE-2023-4966"

[meta]
collected_at = "2026-07-10T21:02:44.534492793+00:00"
status = "completed"

[references]
urls = []
