[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["hwpoc"]
title = "HWPOC-2023-000c9322"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["HWPOC-2023-000c9322"]
ave_id = "AVE-2023-0007"
cve_id = "HWPOC-2023-000c9322"

[meta]
collected_at = "2026-07-10T21:58:39.651154600+00:00"
status = "completed"

[references]
urls = []
