[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["hwpoc"]
title = "HWPOC-2023-000f79a9"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["HWPOC-2023-000f79a9"]
ave_id = "AVE-2023-0009"
cve_id = "HWPOC-2023-000f79a9"

[meta]
collected_at = "2026-07-11T00:05:32.118131041+00:00"
status = "completed"

[references]
urls = []
