[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["hwpoc"]
title = "CVE-2023-46747"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2023-46747"]
ave_id = "AVE-2023-0002"
cve_id = "CVE-2023-46747"

[meta]
collected_at = "2026-07-10T20:58:35.587181308+00:00"
status = "completed"

[references]
urls = []
