[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["hwpoc"]
title = "HWPOC-2023-001b7ef1"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["HWPOC-2023-001b7ef1"]
ave_id = "AVE-2023-0011"
cve_id = "HWPOC-2023-001b7ef1"

[meta]
collected_at = "2026-07-11T01:21:13.764495967+00:00"
status = "completed"

[references]
urls = []
