[basic]
description = ""
published = ""
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 0.0
severity = "UNKNOWN"
sources = ["msrc"]
title = "CVE-2021-47658 漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2021-47658"]
ave_id = "AVE-2021-0001"
cve_id = "CVE-2021-47658"

[meta]
collected_at = "2026-07-10T21:31:19.954875229+00:00"
status = "completed"

[references]
urls = []
