[basic]
description = "Vulnerability identified as CVE-2001-0735. Please refer to vendor advisory for details."
published = "2026-07-10"
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 8.8
severity = "HIGH"
sources = ["osv"]
title = "CVE-2001-0735"
updated = "2026-07-10"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2001-0735"]
ave_id = "AVE-2001-0001"
cve_id = "CVE-2001-0735"

[meta]
collected_at = "2026-07-10T11:14:54.177886780+00:00"
status = "completed"

[references]
urls = []

[score]
cvss_v2 = 7.5
cvss_v2_vector = "AV:N/AC:L/Au:N/C:P/I:P/A:P"
cvss_v3 = 8.8
cvss_v3_vector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
cvss_v4 = 0.0
cvss_v4_vector = ""
