[basic]
description = ""
published = ""
remediation = "请参考官方安全公告，及时安装安全更新或升级到最新版本。"
score = 5
severity = "MEDIUM"
sources = ["avd"]
title = "** REJECT **"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2001-1591"]
ave_id = "AVE-2001-0017"

[meta]
collected_at = "2026-07-11T22:54:47.531553984+00:00"
status = "completed"

[references]
urls = []
