[basic]
description = "Vulnerability identified as CVE-2001-1505. Please refer to vendor advisory for details."
published = "2026-07-10"
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 5.0
severity = "MEDIUM"
sources = ["osv"]
title = "Vulnerability in CVE-2001-1505"
updated = "2026-07-10"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2001-1505"]
ave_id = "AVE-2001-0008"
cve_id = "CVE-2001-1505"

[meta]
collected_at = "2026-07-10T12:52:02.304990113+00:00"
status = "completed"

[references]
urls = []
