[basic]
description = "Vulnerability identified as CVE-2008-0015. Please refer to vendor advisory for details."
published = "2026-07-10"
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 5.0
severity = "MEDIUM"
sources = ["kev"]
title = "Security vulnerability (CVE-2008-0015)"
updated = "2026-07-10"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2008-0015"]
ave_id = "AVE-2008-0001"
cve_id = "CVE-2008-0015"

[meta]
collected_at = "2026-07-10T18:11:00.447720030+00:00"
status = "completed"

[references]
urls = []
