[basic]
description = "Vulnerability identified as CVE-2008-1018. Please refer to vendor advisory for details."
published = "2026-07-10"
remediation = "Refer to vendor advisory and upgrade to fixed version."
score = 5.0
severity = "MEDIUM"
sources = ["tenable"]
title = "CVE-2008-1018 vulnerability"
updated = "2026-07-10"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2008-1018"]
ave_id = "AVE-2008-0012"
cve_id = "CVE-2008-1018"

[meta]
collected_at = "2026-07-10T12:52:47.983939764+00:00"
status = "completed"

[references]
urls = []
